import { getCurrentUser } from '@/lib/auth'
import { notFound, redirect } from 'next/navigation'
import Link from 'next/link'
import { getCustomerLedger } from '@/lib/domain/customers'
import { formatCurrency } from '@/lib/utils/money'
import PrintButton from '@/components/suppliers/PrintButton'

function entryLabel(type: string) {
  switch (type) {
    case 'PAYMENT_RECEIVED':
      return 'Payment received'
    case 'SALE_UDHAAR':
      return 'Sale (udhaar)'
    default:
      return 'Adjustment / opening'
  }
}

export default async function CustomerStatementPage({
  params,
}: {
  params: { id: string }
}) {
  const user = await getCurrentUser()
  if (!user) redirect('/login')

  let data
  try {
    data = await getCustomerLedger(params.id, user.id)
  } catch {
    return notFound()
  }

  const { customer, balance, entries } = data

  // Oldest-first with a running balance owed (DEBIT increases, CREDIT decreases).
  const ordered = [...entries].reverse()
  let running = 0
  const rows = ordered.map((e) => {
    running += e.direction === 'DEBIT' ? e.amount : -e.amount
    return { ...e, running }
  })

  const generatedAt = new Date()

  return (
    <div className="p-6">
      <style>{`
        @media print {
          body * { visibility: hidden; }
          #customer-statement, #customer-statement * { visibility: visible; }
          #customer-statement { position: absolute; left: 0; top: 0; width: 100%; padding: 0; }
          .no-print { display: none !important; }
          @page { size: A4; margin: 14mm; }
        }
      `}</style>

      <div className="no-print mb-4 flex items-center justify-between">
        <Link href={`/store/customers/${customer.id}`} className="btn btn-outline h-9 px-4">
          Back
        </Link>
        <PrintButton />
      </div>

      <div id="customer-statement" className="mx-auto max-w-3xl bg-white text-black">
        <div className="flex items-start justify-between border-b-2 border-black pb-3 mb-4">
          <div>
            <div className="text-xl font-bold">{customer.shopName || 'Customer Statement'}</div>
            <div className="text-sm">Customer Account Statement</div>
          </div>
          <div className="text-right text-sm">
            <div>Date: {generatedAt.toLocaleDateString()}</div>
          </div>
        </div>

        <div className="mb-4 text-sm">
          <div>
            <span className="font-semibold">Customer:</span> {customer.name}
          </div>
          {customer.phone && (
            <div>
              <span className="font-semibold">Phone:</span> {customer.phone}
            </div>
          )}
        </div>

        <table className="w-full text-sm border-collapse">
          <thead>
            <tr className="border-b-2 border-black">
              <th className="text-left py-1.5">Date</th>
              <th className="text-left py-1.5">Description</th>
              <th className="text-right py-1.5">Udhaar</th>
              <th className="text-right py-1.5">Paid</th>
              <th className="text-right py-1.5">Balance</th>
            </tr>
          </thead>
          <tbody>
            {rows.length === 0 ? (
              <tr>
                <td colSpan={5} className="py-3 text-center">
                  No transactions.
                </td>
              </tr>
            ) : (
              rows.map((r) => (
                <tr key={r.id} className="border-b border-gray-300">
                  <td className="py-1.5">{new Date(r.createdAt).toLocaleDateString()}</td>
                  <td className="py-1.5">{entryLabel(r.type)}</td>
                  <td className="text-right py-1.5">
                    {r.direction === 'DEBIT' ? formatCurrency(r.amount) : '-'}
                  </td>
                  <td className="text-right py-1.5">
                    {r.direction === 'CREDIT' ? formatCurrency(r.amount) : '-'}
                  </td>
                  <td className="text-right py-1.5 font-medium">{formatCurrency(r.running)}</td>
                </tr>
              ))
            )}
          </tbody>
          <tfoot>
            <tr className="border-t-2 border-black">
              <td colSpan={4} className="py-2 text-right font-bold">
                Balance Receivable
              </td>
              <td className="py-2 text-right font-bold">{formatCurrency(balance)}</td>
            </tr>
          </tfoot>
        </table>

        <div className="mt-6 text-xs text-gray-600">
          Generated by CartPOS on {generatedAt.toLocaleString()}.
        </div>
      </div>
    </div>
  )
}
