-- Adds more business types to the OrganizationType enum (Pakistani retail).
-- Idempotent: ADD VALUE IF NOT EXISTS. Safe to run against production.

ALTER TYPE "OrganizationType" ADD VALUE IF NOT EXISTS 'KIRYANA_STORE';
ALTER TYPE "OrganizationType" ADD VALUE IF NOT EXISTS 'MOBILE_ACCESSORIES';
ALTER TYPE "OrganizationType" ADD VALUE IF NOT EXISTS 'FOOTWEAR_STORE';
ALTER TYPE "OrganizationType" ADD VALUE IF NOT EXISTS 'COSMETICS_STORE';
ALTER TYPE "OrganizationType" ADD VALUE IF NOT EXISTS 'JEWELRY_STORE';
ALTER TYPE "OrganizationType" ADD VALUE IF NOT EXISTS 'OPTICAL_STORE';
ALTER TYPE "OrganizationType" ADD VALUE IF NOT EXISTS 'HARDWARE_STORE';
ALTER TYPE "OrganizationType" ADD VALUE IF NOT EXISTS 'SANITARY_STORE';
ALTER TYPE "OrganizationType" ADD VALUE IF NOT EXISTS 'AUTO_PARTS';
ALTER TYPE "OrganizationType" ADD VALUE IF NOT EXISTS 'STATIONERY_STORE';
ALTER TYPE "OrganizationType" ADD VALUE IF NOT EXISTS 'BAKERY';
ALTER TYPE "OrganizationType" ADD VALUE IF NOT EXISTS 'RESTAURANT';
ALTER TYPE "OrganizationType" ADD VALUE IF NOT EXISTS 'FURNITURE_STORE';
